- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "car_cmd_vel"
  gz_topic_name: "/model/simple_car/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# R1 Individual Wheel Velocity Control
- ros_topic_name: "/model/R1/joint/front_left_wheel_joint/cmd_vel"
  gz_topic_name: "/model/R1/joint/front_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/model/R1/joint/front_right_wheel_joint/cmd_vel"
  gz_topic_name: "/model/R1/joint/front_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/model/R1/joint/back_left_wheel_joint/cmd_vel"
  gz_topic_name: "/model/R1/joint/back_left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/model/R1/joint/back_right_wheel_joint/cmd_vel"
  gz_topic_name: "/model/R1/joint/back_right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ


- ros_topic_name: "/R2/cmd_vel"
  gz_topic_name: "/model/R2/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Individual Wheel Control
- ros_topic_name: "/R2/front_left_wheel/cmd_torque"
  gz_topic_name: "/model/R2/joint/front_left_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
#   gz_type_name: "gz.msgs.Double"<?xml version="1.0" ?>
# <sdf version="1.8">
#   <world name="test_world">
#     <physics name="1ms" type="ignored">
#       <max_step_size>0.001</max_step_size>
#       <real_time_factor>1.0</real_time_factor>
#     </physics>
#     <plugin
#       filename="gz-sim-physics-system"
#       name="gz::sim::systems::Physics">
#     </plugin>
#     <plugin
#       filename="gz-sim-user-commands-system"
#       name="gz::sim::systems::UserCommands">
#     </plugin>
#     <plugin
#       filename="gz-sim-scene-broadcaster-system"
#       name="gz::sim::systems::SceneBroadcaster">
#     </plugin>

#     <light type="directional" name="sun">
#       <cast_shadows>true</cast_shadows>
#       <pose>0 0 10 0 0 0</pose>
#       <diffuse>0.8 0.8 0.8 1</diffuse>
#       <specular>0.2 0.2 0.2 1</specular>
#       <attenuation>
#         <range>1000</range>
#         <constant>0.9</constant>
#         <linear>0.01</linear>
#         <quadratic>0.001</quadratic>
#       </attenuation>
#       <direction>-0.5 0.1 -0.9</direction>
#     </light>

#     <model name="ground_plane">
#       <static>true</static>
#       <link name="link">
#         <collision name="collision">
#           <geometry>
#             <plane>
#               <normal>0 0 1</normal>
#               <size>100 100</size>
#             </plane>
#           </geometry>
#         </collision>
#         <visual name="visual">
#           <geometry>
#             <plane>
#               <normal>0 0 1</normal>
#               <size>100 100</size>
#             </plane>
#           </geometry>
#           <material>
#             <ambient>0.8 0.8 0.8 1</ambient>
#             <diffuse>0.8 0.8 0.8 1</diffuse>
#             <specular>0.8 0.8 0.8 1</specular>
#           </material>
#         </visual>
#       </link>
#     </model>

#     <!-- R1 Robot -->
#     <include>
#       <name>R1</name>
#       <uri>model://R1</uri>
#       <pose>0 -1.5 0.5 0 0 0</pose>
#     </include>

#     <!-- R2 Robot -->
#     <include>
#       <name>R2</name>
#       <uri>model://R2</uri>
#       <pose>0 1.5 0.5 0 0 0</pose>
#     </include>

#   </world>
# </sdf>

  direction: ROS_TO_GZ

- ros_topic_name: "/R2/front_right_wheel/cmd_torque"
  gz_topic_name: "/model/R2/joint/front_right_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/mid_left_wheel/cmd_torque"
  gz_topic_name: "/model/R2/joint/mid_left_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/mid_right_wheel/cmd_torque"
  gz_topic_name: "/model/R2/joint/mid_right_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/back_left_wheel/cmd_torque"
  gz_topic_name: "/model/R2/joint/back_left_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/R2/back_right_wheel/cmd_torque"
  gz_topic_name: "/model/R2/joint/back_right_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Mini Car Velocity Control
- ros_topic_name: "/mini_car/left_wheel/cmd_vel"
  gz_topic_name: "/model/mini_car/joint/left_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/mini_car/right_wheel/cmd_vel"
  gz_topic_name: "/model/mini_car/joint/right_wheel_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
