controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint_new
      - joint2
      - joint3
      - joint4
      - finger_left_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    allow_partial_joints_goal: true