<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rrr_robot">

  <xacro:property name="link1_len" value="0.2"/>
  <xacro:property name="link1b_len" value="2.7"/>
  <xacro:property name="link2_len" value="2.7"/>
  <xacro:property name="link3_len" value="3.5"/>
  <xacro:property name="link_rad" value="0.2"/>

  <material name="blue"><color rgba="0 0 0.8 1"/></material>
  <material name="green"><color rgba="0 0.8 0 1"/></material>
  <material name="red"><color rgba="0.8 0 0 1"/></material>
  <material name="grey"><color rgba="0.2 0.2 0.2 1"/></material>

  <link name="base_link">
    <visual>
      <geometry><cylinder length="0.1" radius="0.15"/></geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="0 0 ${link1_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${link1_len}" radius="${link_rad}"/></geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="joint_new" type="revolute">
    <parent link="link1"/>
    <child link="link1_b"/>
    <origin xyz="0 0 ${link1_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="link1_b">
    <visual>
      <origin xyz="0 0 ${link1b_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${link1b_len}" radius="${link_rad}"/></geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1_b"/>
    <child link="link2"/>
    <origin xyz="0 0 ${link1b_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 ${link2_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${link2_len}" radius="${link_rad}"/></geometry>
      <material name="green"/>
    </visual>
  </link>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${link2_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="0 0 ${link3_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${link3_len}" radius="${link_rad}"/></geometry>
      <material name="red"/>
    </visual>
  </link>

  <!-- Gripper Base -->
  <!-- Gripper Base (Wrist Roll Joint) -->
  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 ${link3_len}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="gripper_base">
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry><box size="0.2 3 0.2"/></geometry>
      <material name="grey"/>
    </visual>
  </link>

  <!-- Left Finger -->
  <joint name="finger_left_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="gripper_finger_left"/>
    <origin xyz="0 1.0 0.3" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.9" upper="0.5" effort="10.0" velocity="0.5"/>
  </joint>

  <link name="gripper_finger_left">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.1 0.1 0.4"/></geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- Right Finger -->
  <joint name="finger_right_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="gripper_finger_right"/>
    <origin xyz="0 -1.0 0.3" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit lower="-1.0" upper="0.5" effort="10.0" velocity="0.5"/>
    <mimic joint="finger_left_joint" multiplier="1.0" offset="0.0"/>
  </joint>

  <link name="gripper_finger_right">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.1 0.1 0.4"/></geometry>
      <material name="blue"/>
    </visual>
  </link>
</robot>