<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rrr_robot">

  <xacro:property name="link_len" value="0.4"/>
  <xacro:property name="link_rad" value="0.05"/>

  <material name="blue"><color rgba="0 0 0.8 1"/></material>
  <material name="green"><color rgba="0 0.8 0 1"/></material>
  <material name="red"><color rgba="0.8 0 0 1"/></material>
  <material name="grey"><color rgba="0.2 0.2 0.2 1"/></material>

  <link name="base_link">
    <visual>
      <geometry><cylinder length="0.1" radius="0.15"/></geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="0 0 ${link_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${link_len}" radius="${link_rad}"/></geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${link_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 ${link_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${link_len}" radius="${link_rad*0.8}"/></geometry>
      <material name="green"/>
    </visual>
  </link>

  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${link_len}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.5" upper="2.5" effort="10.0" velocity="1.0"/>
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="0 0 ${link_len/2}" rpy="0 0 0"/>
      <geometry><cylinder length="${link_len}" radius="${link_rad*0.6}"/></geometry>
      <material name="red"/>
    </visual>
  </link>
</robot>